def print_menu():
    print("*"*70)
    print("THE MENU IS:\n")
    print("-> 1 to load the graph from file")
    print("-> 2 to get the number of vertices")
    print("-> 3 to see all the vertices")
    print("-> 4 to print the OUT and IN degree of a vertex")
    print("-> 5 to modify the cost of an edge")
    print("-> 6 to verify if there is an edge from <v1> to <v2>")
    print("-> 7 to add an isolated vertex")
    print("-> 8 to add an edge")
    print("-> 9 to remove a vertex")
    print("-> 10 to remove an edge")
    print("-> 11 to make a copy of a graph")
    print("-> 12 to print the graph vertices and edges")
    print("-> 13 to print the copy of the graph ( vertices and edges )")
    print("-> 14 to parse a vertex")
    print("-> 15 to print the isolated vertices")
    print("-> 16 to save to a new file")
    print("-> 17 generate random graph and write it to a file")
    print("-> 18 for the lowest cost between 2 vertices")
    print("-> exit ")
    print("*"*70)